/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(terminos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
  
  result = argp->t1 + argp->t2; 

	return &result;
}

float *
resta_1_svc(terminos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 
	result = argp->t1 - argp->t2; 

	return &result;
}

float *
prod_1_svc(terminos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 
  result = argp->t1 * argp->t2; 

	return &result;
}

float *
div_1_svc(terminos *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

  result = argp->t1 / argp->t2; 

	return &result;
}

float *
pot_1_svc(t_potencia *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

  int i=0; 
  for(i=0; i < argp->exp; i++)
  {
    result = argp->t1;   
  }

	return &result;
}
