/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>


void
programa_calculadora_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	terminos  suma_1_arg;
	float  *result_2;
	terminos  resta_1_arg;
	float  *result_3;
	terminos  prod_1_arg;
	float  *result_4;
	terminos  div_1_arg;
	float  *result_5;
	t_potencia  pot_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_CALCULADORA, VERSION_CALCULADORA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = prod_1(&prod_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = pot_1(&pot_1_arg, clnt);
	if (result_5 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
	
  /* Codigo agregado por el programador */

  terminos t; 
  t.t1 = 2.0;
  t.t2 = 3.0;
  float * resultado_s; 
    
  t_potencia p; 
  p.t1 = 4.0;
  p.exp = 2; 
  float * resultado_p; 

  resultado_s = suma_1(&t, clnt);
  resultado_p = pot_1(&p, clnt);
  

  printf("Suma => %lf + %lf = %lf \n ", t.t1, t.t2, *resultado_s);
  printf("Potencia => %lf ^ %d = %lf \n ", p.t1, p.exp, *resultado_p);

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */



}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_calculadora_1 (host);
exit (0);
}
