/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct terminos {
	float t1;
	float t2;
};
typedef struct terminos terminos;

struct t_potencia {
	float t1;
	int exp;
};
typedef struct t_potencia t_potencia;

#define PROGRAMA_CALCULADORA 0x12345671
#define VERSION_CALCULADORA 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(terminos *, CLIENT *);
extern  float * suma_1_svc(terminos *, struct svc_req *);
#define resta 2
extern  float * resta_1(terminos *, CLIENT *);
extern  float * resta_1_svc(terminos *, struct svc_req *);
#define prod 3
extern  float * prod_1(terminos *, CLIENT *);
extern  float * prod_1_svc(terminos *, struct svc_req *);
#define div 4
extern  float * div_1(terminos *, CLIENT *);
extern  float * div_1_svc(terminos *, struct svc_req *);
#define pot 5
extern  float * pot_1(t_potencia *, CLIENT *);
extern  float * pot_1_svc(t_potencia *, struct svc_req *);
extern int programa_calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define prod 3
extern  float * prod_1();
extern  float * prod_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
#define pot 5
extern  float * pot_1();
extern  float * pot_1_svc();
extern int programa_calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_terminos (XDR *, terminos*);
extern  bool_t xdr_t_potencia (XDR *, t_potencia*);

#else /* K&R C */
extern bool_t xdr_terminos ();
extern bool_t xdr_t_potencia ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
